"""medical: medical_billing_records

Revision ID: 0ea9c1eb22ce
Revises: eb73bbb40cbc
Create Date: 2026-09-11 01:36:20.306809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea9c1eb22ce'
down_revision: Union[str, Sequence[str], None] = 'eb73bbb40cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_billing_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('consultation_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('professional_user_id', sa.BigInteger(), nullable=False),
    sa.Column('billing_mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='issued', nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='HNL', nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("billing_mode IN ('accounting_invoice', 'simple_receipt')", name='ck_medical_billing_records_mode'),
    sa.CheckConstraint("status IN ('issued', 'cancelled')", name='ck_medical_billing_records_status'),
    sa.CheckConstraint('amount > 0', name='ck_medical_billing_records_amount_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['patient_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['professional_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_billing_records_company_id'), 'medical_billing_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_medical_billing_records_consultation_id'), 'medical_billing_records', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_medical_billing_records_patient_contact_id'), 'medical_billing_records', ['patient_contact_id'], unique=False)
    op.create_index(op.f('ix_medical_billing_records_professional_user_id'), 'medical_billing_records', ['professional_user_id'], unique=False)
    # ### end Alembic commands ###
    # NOTA: se removieron 4 líneas autogeneradas erróneas acá (mismo falso
    # positivo documentado en cada migración desde purchasing).

    op.execute("ALTER TABLE medical_billing_records ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE medical_billing_records FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON medical_billing_records
            USING (company_id = current_setting('app.current_company_id', true)::bigint)
            WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON medical_billing_records TO erp_app")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON medical_billing_records")
    op.execute("ALTER TABLE medical_billing_records NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE medical_billing_records DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_billing_records_professional_user_id'), table_name='medical_billing_records')
    op.drop_index(op.f('ix_medical_billing_records_patient_contact_id'), table_name='medical_billing_records')
    op.drop_index(op.f('ix_medical_billing_records_consultation_id'), table_name='medical_billing_records')
    op.drop_index(op.f('ix_medical_billing_records_company_id'), table_name='medical_billing_records')
    op.drop_table('medical_billing_records')
    # ### end Alembic commands ###
