"""medical: clinical_record_entries, appointments, consultations

Revision ID: 1669f8fbbc6b
Revises: eefbf14931c3
Create Date: 2026-09-09 04:10:46.008324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1669f8fbbc6b'
down_revision: Union[str, Sequence[str], None] = 'eefbf14931c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('professional_user_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('scheduled', 'confirmed', 'completed', 'cancelled', 'no_show')", name='ck_appointments_status'),
    sa.CheckConstraint('scheduled_end > scheduled_start', name='ck_appointments_end_after_start'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['professional_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_company_id'), 'appointments', ['company_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_contact_id'), 'appointments', ['patient_contact_id'], unique=False)
    op.create_index(op.f('ix_appointments_professional_user_id'), 'appointments', ['professional_user_id'], unique=False)
    op.create_table('clinical_record_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('previous_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('author_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('antecedent', 'allergy', 'diagnosis', 'note')", name='ck_clinical_record_entries_type'),
    sa.CheckConstraint('previous_entry_id IS NULL OR previous_entry_id <> id', name='ck_clinical_record_entries_not_own_previous'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['patient_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['previous_entry_id'], ['clinical_record_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_record_entries_company_id'), 'clinical_record_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_clinical_record_entries_patient_contact_id'), 'clinical_record_entries', ['patient_contact_id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('professional_user_id', sa.BigInteger(), nullable=False),
    sa.Column('physical_exam', sa.LargeBinary(), nullable=True),
    sa.Column('diagnosis_cie10', sa.String(length=10), nullable=True),
    sa.Column('diagnosis_text', sa.LargeBinary(), nullable=True),
    sa.Column('treatment_plan', sa.LargeBinary(), nullable=True),
    sa.Column('previous_consultation_id', sa.BigInteger(), nullable=True),
    sa.Column('superseded_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('previous_consultation_id IS NULL OR previous_consultation_id <> id', name='ck_consultations_not_own_previous'),
    sa.CheckConstraint('superseded_by_id IS NULL OR superseded_by_id <> id', name='ck_consultations_not_own_superseder'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['previous_consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['professional_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_appointment_id'), 'consultations', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_consultations_company_id'), 'consultations', ['company_id'], unique=False)
    op.create_index(op.f('ix_consultations_patient_contact_id'), 'consultations', ['patient_contact_id'], unique=False)
    op.create_index(op.f('ix_consultations_professional_user_id'), 'consultations', ['professional_user_id'], unique=False)
    # ### end Alembic commands ###
    # NOTA: se removieron 4 líneas autogeneradas erróneas acá (mismo falso
    # positivo documentado en cada migración desde purchasing).

    # -----------------------------------------------------------------
    # DED-25 (revisado en el cierre de Fase 4 — hallazgo real de tests):
    # se intentó un índice único parcial `WHERE superseded_by_id IS NULL`
    # para "una sola consulta vigente por cita", pero un índice único
    # parcial de Postgres NO es diferible (`ALTER TABLE ... ADD CONSTRAINT
    # ... UNIQUE ... DEFERRABLE` no admite cláusula WHERE) — se dispara en
    # cuanto se inserta la fila de corrección, antes de poder desmarcar la
    # anterior como superseded en la misma transacción. Revertido: el
    # invariante se garantiza por bloqueo de fila real, no por constraint:
    # `AppointmentService._get_locked` (`SELECT ... FOR UPDATE` sobre la
    # cita) serializa `ConsultationService.create`, y el `SELECT ... FOR
    # UPDATE` sobre la consulta anterior en `ConsultationService.correct`
    # serializa correcciones concurrentes sobre la misma fila. Ver test
    # `test_consultation_correction_never_overwrites` (control de
    # concurrencia) y `test_consultation_only_one_per_appointment`.
    # -----------------------------------------------------------------

    # -----------------------------------------------------------------
    # HALLAZGO REAL (regresión QA, primera corrida contra Postgres real):
    # `app/medical/services.py` usa func.pgp_sym_encrypt/pgp_sym_decrypt
    # (pgcrypto) para cifrar clinical_record_entries.content y los campos
    # clínicos de consultations (DED-24/DED-25 en STATE.md), pero ninguna
    # migración del repo habilitaba la extensión pgcrypto — mismo tipo de
    # bug que el de pg_trgm en contacts (40b15e2afd9b), nunca detectado
    # porque ninguna sesión de chat anterior tuvo Postgres real. Sin esto,
    # cualquier INSERT/UPDATE sobre estas columnas habría fallado en
    # cuanto se ejecutara por primera vez contra una base real.
    # -----------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # -----------------------------------------------------------------
    # DED-26: bloqueo de horario real — un profesional no puede tener dos
    # citas activas (scheduled/confirmed) que se traslapen en el tiempo.
    # EXCLUDE USING gist requiere btree_gist para comparar el bigint de
    # professional_user_id por igualdad dentro de la misma restricción de
    # exclusión que compara el tsrange por solapamiento.
    # -----------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        ALTER TABLE appointments
            ADD CONSTRAINT excl_appointments_professional_overlap
            EXCLUDE USING gist (
                professional_user_id WITH =,
                tstzrange(scheduled_start, scheduled_end, '[)') WITH &&
            ) WHERE (status IN ('scheduled', 'confirmed'))
        """
    )

    # -----------------------------------------------------------------
    # RLS + tenant_isolation + grants — mismo patrón que todas las
    # migraciones anteriores, las 3 tablas nuevas de medical.
    # -----------------------------------------------------------------
    medical_tables = ("clinical_record_entries", "appointments", "consultations")
    for table_name in medical_tables:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table_name}
                USING (company_id = current_setting('app.current_company_id', true)::bigint)
                WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
            """
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO erp_app")


def downgrade() -> None:
    """Downgrade schema."""
    medical_tables = ("clinical_record_entries", "appointments", "consultations")
    for table_name in medical_tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table_name}")
        op.execute(f"ALTER TABLE {table_name} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} DISABLE ROW LEVEL SECURITY")

    op.execute("ALTER TABLE appointments DROP CONSTRAINT IF EXISTS excl_appointments_professional_overlap")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultations_patient_contact_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_company_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_appointment_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_clinical_record_entries_patient_contact_id'), table_name='clinical_record_entries')
    op.drop_index(op.f('ix_clinical_record_entries_company_id'), table_name='clinical_record_entries')
    op.drop_table('clinical_record_entries')
    op.drop_index(op.f('ix_appointments_professional_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_contact_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_company_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
