"""medical: lab_orders, lab_order_tests

Revision ID: 1d195275df90
Revises: b2d5b9c45497
Create Date: 2026-09-10 10:16:44.273242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d195275df90'
down_revision: Union[str, Sequence[str], None] = 'b2d5b9c45497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('consultation_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('professional_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ordered', nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("status IN ('ordered', 'completed', 'cancelled')", name='ck_lab_orders_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['professional_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_orders_company_id'), 'lab_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_consultation_id'), 'lab_orders', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_patient_contact_id'), 'lab_orders', ['patient_contact_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_professional_user_id'), 'lab_orders', ['professional_user_id'], unique=False)
    op.create_table('lab_order_tests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('lab_order_id', sa.BigInteger(), nullable=False),
    sa.Column('test_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('result_value', sa.String(length=300), nullable=True),
    sa.Column('result_unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range_text', sa.String(length=200), nullable=True),
    sa.Column('is_critical', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resulted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resulted_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'resulted')", name='ck_lab_order_tests_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lab_order_id'], ['lab_orders.id'], ),
    sa.ForeignKeyConstraint(['resulted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_order_tests_company_id'), 'lab_order_tests', ['company_id'], unique=False)
    op.create_index(op.f('ix_lab_order_tests_lab_order_id'), 'lab_order_tests', ['lab_order_id'], unique=False)
    # ### end Alembic commands ###
    # NOTA: se removieron 4 líneas autogeneradas erróneas acá (mismo falso
    # positivo documentado en cada migración desde purchasing).

    lab_tables = ("lab_orders", "lab_order_tests")
    for table_name in lab_tables:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table_name}
                USING (company_id = current_setting('app.current_company_id', true)::bigint)
                WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
            """
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO erp_app")


def downgrade() -> None:
    """Downgrade schema."""
    lab_tables = ("lab_orders", "lab_order_tests")
    for table_name in lab_tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table_name}")
        op.execute(f"ALTER TABLE {table_name} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_order_tests_lab_order_id'), table_name='lab_order_tests')
    op.drop_index(op.f('ix_lab_order_tests_company_id'), table_name='lab_order_tests')
    op.drop_table('lab_order_tests')
    op.drop_index(op.f('ix_lab_orders_professional_user_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_patient_contact_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_consultation_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_company_id'), table_name='lab_orders')
    op.drop_table('lab_orders')
    # ### end Alembic commands ###
