"""medical: patient_messages

Revision ID: 370fd33db300
Revises: 0ea9c1eb22ce
Create Date: 2026-09-11 23:04:27.417906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370fd33db300'
down_revision: Union[str, Sequence[str], None] = '0ea9c1eb22ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('professional_user_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('author_user_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sender_role IN ('professional', 'patient')", name='ck_patient_messages_sender_role'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['patient_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['professional_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_messages_company_id'), 'patient_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_patient_messages_created_at'), 'patient_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_messages_patient_contact_id'), 'patient_messages', ['patient_contact_id'], unique=False)
    op.create_index(op.f('ix_patient_messages_professional_user_id'), 'patient_messages', ['professional_user_id'], unique=False)
    # ### end Alembic commands ###
    # NOTA: se removieron 4 líneas autogeneradas erróneas acá (mismo falso
    # positivo documentado en cada migración desde purchasing).

    op.execute("ALTER TABLE patient_messages ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE patient_messages FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON patient_messages
            USING (company_id = current_setting('app.current_company_id', true)::bigint)
            WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON patient_messages TO erp_app")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON patient_messages")
    op.execute("ALTER TABLE patient_messages NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE patient_messages DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_messages_professional_user_id'), table_name='patient_messages')
    op.drop_index(op.f('ix_patient_messages_patient_contact_id'), table_name='patient_messages')
    op.drop_index(op.f('ix_patient_messages_created_at'), table_name='patient_messages')
    op.drop_index(op.f('ix_patient_messages_company_id'), table_name='patient_messages')
    op.drop_table('patient_messages')
    # ### end Alembic commands ###
