"""contacts: entidad unificada con flags de rol

Revision ID: 40b15e2afd9b
Revises: 131bc488d5b7
Create Date: 2026-08-20 05:01:53.188131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b15e2afd9b'
down_revision: Union[str, Sequence[str], None] = '131bc488d5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('is_customer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_vendor', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_patient', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_lead', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    # ### end Alembic commands ###
    # NOTA: se removieron dos líneas autogeneradas erróneas acá
    # (op.drop_constraint sobre ck_company_packages_package/status) — falso
    # positivo del comparador de Alembic: esos CHECK constraints se crearon
    # con op.execute() crudo en la migración 1483b27d4cff (no vía
    # sa.CheckConstraint declarativo), así que no están en los metadatos de
    # SQLAlchemy y el autogenerate los interpreta como "removidos" al
    # comparar contra el modelo. Verificado con \d company_packages antes de
    # aplicar — ver cierre de este módulo.

    # Búsqueda pg_trgm/GIN obligatoria en 'name' (spec 1.1, DoD explícito
    # para contacts).
    op.execute("CREATE INDEX ix_contacts_name_trgm ON contacts USING gin (name gin_trgm_ops)")

    # Row-Level Security (spec 5/DoD) — contacts tiene company_id.
    op.execute("ALTER TABLE contacts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE contacts FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON contacts
            USING (company_id = current_setting('app.current_company_id', true)::bigint)
            WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON contacts TO erp_app")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON contacts")
    op.execute("ALTER TABLE contacts NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE contacts DISABLE ROW LEVEL SECURITY")
    op.execute("DROP INDEX IF EXISTS ix_contacts_name_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
