"""pharmacy: controlled_substance_products, dispensation_orders, dispensation_lines, controlled_substance_log_entries

Revision ID: 465ce93341cd
Revises: 370fd33db300
Create Date: 2026-09-12 19:14:47.814792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465ce93341cd'
down_revision: Union[str, Sequence[str], None] = '370fd33db300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlled_substance_products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'product_id', name='uq_controlled_substance_products_company_product')
    )
    op.create_index(op.f('ix_controlled_substance_products_company_id'), 'controlled_substance_products', ['company_id'], unique=False)
    op.create_index(op.f('ix_controlled_substance_products_product_id'), 'controlled_substance_products', ['product_id'], unique=False)
    op.create_table('dispensation_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('dispensed_by', sa.BigInteger(), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('prescription_id', sa.BigInteger(), nullable=True),
    sa.Column('walk_in_reference', sa.String(length=300), nullable=True),
    sa.Column('allergy_check_source', sa.String(length=20), nullable=False),
    sa.Column('allergy_check_notes', sa.String(length=1000), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('amount_charged', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='dispensed', nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("allergy_check_source IN ('medical_record', 'form')", name='ck_dispensation_orders_allergy_source'),
    sa.CheckConstraint("status IN ('dispensed', 'voided')", name='ck_dispensation_orders_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'document_number', name='uq_dispensation_orders_company_document_number')
    )
    op.create_index(op.f('ix_dispensation_orders_company_id'), 'dispensation_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_dispensation_orders_patient_contact_id'), 'dispensation_orders', ['patient_contact_id'], unique=False)
    op.create_index(op.f('ix_dispensation_orders_warehouse_id'), 'dispensation_orders', ['warehouse_id'], unique=False)
    op.create_table('dispensation_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('dispensation_order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_dispensation_lines_quantity_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['dispensation_order_id'], ['dispensation_orders.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispensation_lines_company_id'), 'dispensation_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_dispensation_lines_dispensation_order_id'), 'dispensation_lines', ['dispensation_order_id'], unique=False)
    op.create_index(op.f('ix_dispensation_lines_product_id'), 'dispensation_lines', ['product_id'], unique=False)
    op.create_table('controlled_substance_log_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('dispensation_line_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('dispensed_by', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['dispensation_line_id'], ['dispensation_lines.id'], ),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlled_substance_log_entries_company_id'), 'controlled_substance_log_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_controlled_substance_log_entries_created_at'), 'controlled_substance_log_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_controlled_substance_log_entries_dispensation_line_id'), 'controlled_substance_log_entries', ['dispensation_line_id'], unique=False)
    op.create_index(op.f('ix_controlled_substance_log_entries_patient_contact_id'), 'controlled_substance_log_entries', ['patient_contact_id'], unique=False)
    op.create_index(op.f('ix_controlled_substance_log_entries_product_id'), 'controlled_substance_log_entries', ['product_id'], unique=False)
    # ### end Alembic commands ###
    # NOTA: se removieron 4 líneas autogeneradas erróneas acá (mismo falso
    # positivo documentado en cada migración desde purchasing).

    pharmacy_tables = ("controlled_substance_products", "dispensation_orders", "dispensation_lines", "controlled_substance_log_entries")
    for table_name in pharmacy_tables:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table_name}
                USING (company_id = current_setting('app.current_company_id', true)::bigint)
                WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
            """
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO erp_app")


def downgrade() -> None:
    """Downgrade schema."""
    pharmacy_tables = ("controlled_substance_products", "dispensation_orders", "dispensation_lines", "controlled_substance_log_entries")
    for table_name in pharmacy_tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table_name}")
        op.execute(f"ALTER TABLE {table_name} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controlled_substance_log_entries_product_id'), table_name='controlled_substance_log_entries')
    op.drop_index(op.f('ix_controlled_substance_log_entries_patient_contact_id'), table_name='controlled_substance_log_entries')
    op.drop_index(op.f('ix_controlled_substance_log_entries_dispensation_line_id'), table_name='controlled_substance_log_entries')
    op.drop_index(op.f('ix_controlled_substance_log_entries_created_at'), table_name='controlled_substance_log_entries')
    op.drop_index(op.f('ix_controlled_substance_log_entries_company_id'), table_name='controlled_substance_log_entries')
    op.drop_table('controlled_substance_log_entries')
    op.drop_index(op.f('ix_dispensation_lines_product_id'), table_name='dispensation_lines')
    op.drop_index(op.f('ix_dispensation_lines_dispensation_order_id'), table_name='dispensation_lines')
    op.drop_index(op.f('ix_dispensation_lines_company_id'), table_name='dispensation_lines')
    op.drop_table('dispensation_lines')
    op.drop_index(op.f('ix_dispensation_orders_warehouse_id'), table_name='dispensation_orders')
    op.drop_index(op.f('ix_dispensation_orders_patient_contact_id'), table_name='dispensation_orders')
    op.drop_index(op.f('ix_dispensation_orders_company_id'), table_name='dispensation_orders')
    op.drop_table('dispensation_orders')
    op.drop_index(op.f('ix_controlled_substance_products_product_id'), table_name='controlled_substance_products')
    op.drop_index(op.f('ix_controlled_substance_products_company_id'), table_name='controlled_substance_products')
    op.drop_table('controlled_substance_products')
    # ### end Alembic commands ###
