"""core+inventory: document_counters, version en stock_levels, FK active_warehouse_id en modelo

Revision ID: 4d97e3604c34
Revises: ccd8a2f53a05
Create Date: 2026-08-22 11:37:37.295966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d97e3604c34'
down_revision: Union[str, Sequence[str], None] = 'ccd8a2f53a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_counters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('current_number', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'doc_type', 'year', name='uq_document_counters_company_type_year')
    )
    op.create_index(op.f('ix_document_counters_company_id'), 'document_counters', ['company_id'], unique=False)
    op.add_column('stock_levels', sa.Column('version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###
    # NOTA: se removieron 3 líneas autogeneradas erróneas acá (mismo falso
    # positivo documentado en migraciones anteriores — CHECK/GIN creados
    # con op.execute() crudo).

    op.execute("ALTER TABLE document_counters ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE document_counters FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON document_counters
            USING (company_id = current_setting('app.current_company_id', true)::bigint)
            WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON document_counters TO erp_app")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON document_counters")
    op.execute("ALTER TABLE document_counters NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE document_counters DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_levels', 'version')
    op.drop_index(op.f('ix_document_counters_company_id'), table_name='document_counters')
    op.drop_table('document_counters')
    # ### end Alembic commands ###
