"""accounting: plan de cuentas, motor de asientos, facturacion, notas, pagos, contact.credit_limit

Revision ID: a5401f4a0ab1
Revises: c93e498bb1c4
Create Date: 2026-08-25 10:17:18.891197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5401f4a0ab1'
down_revision: Union[str, Sequence[str], None] = 'c93e498bb1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rate >= 0 AND rate <= 100', name='ck_tax_rates_rate_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_tax_rates_company_name')
    )
    op.create_index(op.f('ix_tax_rates_company_id'), 'tax_rates', ['company_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("account_type IN ('receivable', 'payable', 'income', 'tax', 'cash_bank', 'adjustment')", name='ck_accounts_account_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_accounts_company_code')
    )
    op.create_index(op.f('ix_accounts_company_id'), 'accounts', ['company_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("document_type IN ('sales_invoice', 'purchase_invoice', 'sales_credit_note', 'sales_debit_note', 'purchase_credit_note', 'purchase_debit_note', 'payment_received', 'payment_made')", name='ck_journal_entries_document_type'),
    sa.CheckConstraint('total_debit = total_credit', name='ck_journal_entries_balanced'),
    sa.CheckConstraint('total_debit >= 0 AND total_credit >= 0', name='ck_journal_entries_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_company_id'), 'journal_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_document_id'), 'journal_entries', ['document_id'], unique=False)
    op.create_table('document_account_mappings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('sales_invoice', 'purchase_invoice', 'sales_credit_note', 'sales_debit_note', 'purchase_credit_note', 'purchase_debit_note', 'payment_received', 'payment_made')", name='ck_doc_account_mappings_document_type'),
    sa.CheckConstraint("role IN ('receivable', 'payable', 'income', 'tax', 'cash_bank', 'adjustment')", name='ck_doc_account_mappings_role'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'document_type', 'role', name='uq_doc_account_mappings_company_type_role')
    )
    op.create_index(op.f('ix_document_account_mappings_company_id'), 'document_account_mappings', ['company_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='HNL', nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('source_document_type', sa.String(length=30), nullable=True),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("direction IN ('sale', 'purchase')", name='ck_invoices_direction'),
    sa.CheckConstraint("status IN ('draft', 'posted', 'partially_paid', 'paid', 'cancelled')", name='ck_invoices_status'),
    sa.CheckConstraint('balance_due >= 0 AND balance_due <= total', name='ck_invoices_balance_due_range'),
    sa.CheckConstraint('subtotal >= 0 AND tax_amount >= 0 AND total >= 0', name='ck_invoices_amounts_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_invoices_company_number')
    )
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_contact_id'), 'invoices', ['contact_id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.CheckConstraint('(debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)', name='ck_journal_lines_debit_xor_credit'),
    sa.CheckConstraint('debit >= 0 AND credit >= 0', name='ck_journal_lines_nonneg'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_account_id'), 'journal_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_company_id'), 'journal_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_journal_entry_id'), 'journal_lines', ['journal_entry_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("direction IN ('sale', 'purchase')", name='ck_payments_direction'),
    sa.CheckConstraint("method IN ('cash', 'bank_transfer', 'card', 'check', 'other')", name='ck_payments_method'),
    sa.CheckConstraint("status IN ('draft', 'posted', 'cancelled')", name='ck_payments_status'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_payments_company_number')
    )
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_contact_id'), 'payments', ['contact_id'], unique=False)
    op.create_table('credit_debit_notes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('note_type', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("direction IN ('sale', 'purchase')", name='ck_credit_debit_notes_direction'),
    sa.CheckConstraint("note_type IN ('credit', 'debit')", name='ck_credit_debit_notes_note_type'),
    sa.CheckConstraint("status IN ('draft', 'posted', 'cancelled')", name='ck_credit_debit_notes_status'),
    sa.CheckConstraint('subtotal >= 0 AND tax_amount >= 0 AND total >= 0', name='ck_credit_debit_notes_amounts_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_credit_debit_notes_company_number')
    )
    op.create_index(op.f('ix_credit_debit_notes_company_id'), 'credit_debit_notes', ['company_id'], unique=False)
    op.create_index(op.f('ix_credit_debit_notes_contact_id'), 'credit_debit_notes', ['contact_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rate_id', sa.BigInteger(), nullable=True),
    sa.Column('line_subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('line_subtotal >= 0 AND line_tax >= 0 AND line_total >= 0', name='ck_invoice_lines_amounts_nonneg'),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_lines_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_invoice_lines_unit_price_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_company_id'), 'invoice_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_applied > 0', name='ck_payment_allocations_amount_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocations_company_id'), 'payment_allocations', ['company_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_invoice_id'), 'payment_allocations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_table('credit_debit_note_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rate_id', sa.BigInteger(), nullable=True),
    sa.Column('line_subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('line_subtotal >= 0 AND line_tax >= 0 AND line_total >= 0', name='ck_cdn_lines_amounts_nonneg'),
    sa.CheckConstraint('quantity > 0', name='ck_cdn_lines_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_cdn_lines_unit_price_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['credit_debit_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_debit_note_lines_company_id'), 'credit_debit_note_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_credit_debit_note_lines_note_id'), 'credit_debit_note_lines', ['note_id'], unique=False)
    op.add_column('contacts', sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###
    # NOTA: se removieron 4 líneas autogeneradas erróneas acá (mismo falso
    # positivo documentado en migraciones anteriores — autogenerate no ve
    # reflejados correctamente objetos creados vía op.execute() crudo en
    # migraciones previas: ck_company_packages_package/status, el índice
    # GIN ix_contacts_name_trgm, ck_stock_levels_reserved_quantity_valid).

    # -----------------------------------------------------------------
    # RLS + tenant_isolation + grants — mismo patrón que purchasing/sales,
    # las 11 tablas nuevas de accounting.
    # -----------------------------------------------------------------
    accounting_tables = (
        "accounts",
        "document_account_mappings",
        "journal_entries",
        "journal_lines",
        "tax_rates",
        "invoices",
        "invoice_lines",
        "credit_debit_notes",
        "credit_debit_note_lines",
        "payments",
        "payment_allocations",
    )
    for table_name in accounting_tables:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table_name}
                USING (company_id = current_setting('app.current_company_id', true)::bigint)
                WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
            """
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO erp_app")

    # -----------------------------------------------------------------
    # Trigger de inmutabilidad (append-only) sobre journal_entries y
    # journal_lines — spec 7.1 ("todo asiento debe balancear... la
    # generación del asiento es atómica"), compliance contable exige que
    # un asiento ya persistido nunca se edite ni borre, se reversa con un
    # asiento de reversión nuevo (Fase 2). Mismo patrón que
    # audit_prevent_update_delete (módulo 1), función separada porque el
    # mensaje de error referencia la tabla real vía TG_TABLE_NAME.
    # -----------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION journal_prevent_update_delete()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION '% es append-only: % no permitido (id=%)',
                TG_TABLE_NAME, TG_OP, OLD.id
                USING ERRCODE = 'insufficient_privilege';
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table_name in ("journal_entries", "journal_lines"):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table_name}_immutable
            BEFORE UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION journal_prevent_update_delete();
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Reversa de triggers de inmutabilidad, RLS antes de tocar las tablas
    # (orden inverso al upgrade, mismo criterio que migraciones previas).
    for table_name in ("journal_entries", "journal_lines"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_immutable ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS journal_prevent_update_delete()")

    accounting_tables = (
        "accounts",
        "document_account_mappings",
        "journal_entries",
        "journal_lines",
        "tax_rates",
        "invoices",
        "invoice_lines",
        "credit_debit_notes",
        "credit_debit_note_lines",
        "payments",
        "payment_allocations",
    )
    for table_name in accounting_tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table_name}")
        op.execute(f"ALTER TABLE {table_name} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} DISABLE ROW LEVEL SECURITY")

    op.drop_column('contacts', 'credit_limit')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_debit_note_lines_note_id'), table_name='credit_debit_note_lines')
    op.drop_index(op.f('ix_credit_debit_note_lines_company_id'), table_name='credit_debit_note_lines')
    op.drop_table('credit_debit_note_lines')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_invoice_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_company_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_company_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_credit_debit_notes_contact_id'), table_name='credit_debit_notes')
    op.drop_index(op.f('ix_credit_debit_notes_company_id'), table_name='credit_debit_notes')
    op.drop_table('credit_debit_notes')
    op.drop_index(op.f('ix_payments_contact_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_journal_lines_journal_entry_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_company_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_account_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_invoices_contact_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_document_account_mappings_company_id'), table_name='document_account_mappings')
    op.drop_table('document_account_mappings')
    op.drop_index(op.f('ix_journal_entries_document_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_company_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_accounts_company_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_tax_rates_company_id'), table_name='tax_rates')
    op.drop_table('tax_rates')
    # ### end Alembic commands ###
