"""medical: prescriptions, prescription_lines

Revision ID: b2d5b9c45497
Revises: 7129029c1e2c
Create Date: 2026-09-10 04:03:30.267455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d5b9c45497'
down_revision: Union[str, Sequence[str], None] = '7129029c1e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('consultation_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('professional_user_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['professional_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_company_id'), 'prescriptions', ['company_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_consultation_id'), 'prescriptions', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_contact_id'), 'prescriptions', ['patient_contact_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_professional_user_id'), 'prescriptions', ['professional_user_id'], unique=False)
    op.create_table('prescription_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('prescription_id', sa.BigInteger(), nullable=False),
    sa.Column('medication_name', sa.String(length=300), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('dispensing_status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("dispensing_status IN ('not_applicable', 'pending', 'dispensed')", name='ck_prescription_lines_dispensing_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_lines_company_id'), 'prescription_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_prescription_lines_prescription_id'), 'prescription_lines', ['prescription_id'], unique=False)
    # ### end Alembic commands ###
    # NOTA: se removieron 4 líneas autogeneradas erróneas acá (mismo falso
    # positivo documentado en cada migración desde purchasing).

    prescription_tables = ("prescriptions", "prescription_lines")
    for table_name in prescription_tables:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table_name}
                USING (company_id = current_setting('app.current_company_id', true)::bigint)
                WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
            """
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO erp_app")


def downgrade() -> None:
    """Downgrade schema."""
    prescription_tables = ("prescriptions", "prescription_lines")
    for table_name in prescription_tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table_name}")
        op.execute(f"ALTER TABLE {table_name} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_lines_prescription_id'), table_name='prescription_lines')
    op.drop_index(op.f('ix_prescription_lines_company_id'), table_name='prescription_lines')
    op.drop_table('prescription_lines')
    op.drop_index(op.f('ix_prescriptions_professional_user_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_contact_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_consultation_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_company_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    # ### end Alembic commands ###
