"""inventory: reserved_quantity en stock_levels (sales, hallazgo retroactivo)

Revision ID: c93e498bb1c4
Revises: 905a3855ef61
Create Date: 2026-08-23 23:56:03.695413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93e498bb1c4'
down_revision: Union[str, Sequence[str], None] = '905a3855ef61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='HNL', nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_price_lists_company_name')
    )
    op.create_index(op.f('ix_price_lists_company_id'), 'price_lists', ['company_id'], unique=False)
    op.create_table('price_list_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('price_list_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=14, scale=4), server_default='1', nullable=False),
    sa.CheckConstraint('min_quantity > 0', name='ck_price_list_items_min_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_price_list_items_unit_price_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'price_list_id', 'product_id', 'min_quantity', name='uq_price_list_items_list_product_qty')
    )
    op.create_index(op.f('ix_price_list_items_company_id'), 'price_list_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_price_list_items_price_list_id'), 'price_list_items', ['price_list_id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('price_list_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='HNL', nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'en_preparacion', 'enviado', 'facturado', 'cancelado')", name='ck_sales_orders_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_sales_orders_company_number')
    )
    op.create_index(op.f('ix_sales_orders_company_id'), 'sales_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_customer_id'), 'sales_orders', ['customer_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('price_list_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='HNL', nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('converted_to_order_id', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'sent', 'accepted', 'expired', 'cancelled', 'converted')", name='ck_quotes_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['converted_to_order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_quotes_company_number')
    )
    op.create_index(op.f('ix_quotes_company_id'), 'quotes', ['company_id'], unique=False)
    op.create_index(op.f('ix_quotes_customer_id'), 'quotes', ['customer_id'], unique=False)
    op.create_table('sales_order_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('sales_order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_shipped', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sales_order_lines_quantity_positive'),
    sa.CheckConstraint('quantity_shipped >= 0', name='ck_sales_order_lines_quantity_shipped_nonneg'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sales_order_lines_unit_price_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_lines_company_id'), 'sales_order_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_order_lines_sales_order_id'), 'sales_order_lines', ['sales_order_id'], unique=False)
    op.create_table('quote_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('quote_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_quote_lines_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_quote_lines_unit_price_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_lines_company_id'), 'quote_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_quote_lines_quote_id'), 'quote_lines', ['quote_id'], unique=False)
    op.add_column('stock_levels', sa.Column('reserved_quantity', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False))
    # ### end Alembic commands ###
    # NOTA: se removieron 3 líneas autogeneradas erróneas acá (mismo falso
    # positivo documentado en migraciones anteriores).

    # CHECK de defensa en profundidad (spec 5) — reserved_quantity nunca
    # negativo ni mayor al físico. El código de servicio ya lo garantiza
    # (StockService.reserve/ship/release_reservation), esto es la segunda
    # capa a nivel de BD, mismo criterio aplicado en todo el proyecto.
    op.create_check_constraint(
        "ck_stock_levels_reserved_quantity_valid",
        "stock_levels",
        "reserved_quantity >= 0 AND reserved_quantity <= quantity",
    )

    for table_name in ("price_lists", "price_list_items", "sales_orders", "sales_order_lines", "quotes", "quote_lines"):
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table_name}
                USING (company_id = current_setting('app.current_company_id', true)::bigint)
                WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
            """
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO erp_app")


def downgrade() -> None:
    """Downgrade schema."""
    for table_name in ("price_lists", "price_list_items", "sales_orders", "sales_order_lines", "quotes", "quote_lines"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table_name}")
        op.execute(f"ALTER TABLE {table_name} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} DISABLE ROW LEVEL SECURITY")

    op.drop_constraint("ck_stock_levels_reserved_quantity_valid", "stock_levels", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_levels', 'reserved_quantity')
    op.drop_index(op.f('ix_quote_lines_quote_id'), table_name='quote_lines')
    op.drop_index(op.f('ix_quote_lines_company_id'), table_name='quote_lines')
    op.drop_table('quote_lines')
    op.drop_index(op.f('ix_sales_order_lines_sales_order_id'), table_name='sales_order_lines')
    op.drop_index(op.f('ix_sales_order_lines_company_id'), table_name='sales_order_lines')
    op.drop_table('sales_order_lines')
    op.drop_index(op.f('ix_quotes_customer_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_company_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_sales_orders_customer_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_company_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_price_list_items_price_list_id'), table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_company_id'), table_name='price_list_items')
    op.drop_table('price_list_items')
    op.drop_index(op.f('ix_price_lists_company_id'), table_name='price_lists')
    op.drop_table('price_lists')
    # ### end Alembic commands ###
