"""pipeline: stages, opportunities, activities

Revision ID: ce27c6dbddb7
Revises: a5401f4a0ab1
Create Date: 2026-08-27 06:08:29.247834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce27c6dbddb7'
down_revision: Union[str, Sequence[str], None] = 'a5401f4a0ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_won', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_lost', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (is_won AND is_lost)', name='ck_stages_won_xor_lost'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_stages_company_name')
    )
    op.create_index(op.f('ix_stages_company_id'), 'stages', ['company_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), server_default='HNL', nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_reason', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('open', 'won', 'lost')", name='ck_opportunities_status'),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name='ck_opportunities_amount_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_opportunities_contact_id'), 'opportunities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_opportunities_stage_id'), 'opportunities', ['stage_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('activity_type', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("activity_type IN ('call', 'email', 'meeting', 'note', 'task')", name='ck_activities_activity_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_company_id'), 'activities', ['company_id'], unique=False)
    op.create_index(op.f('ix_activities_contact_id'), 'activities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_activities_opportunity_id'), 'activities', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###
    # NOTA: se removieron 4 líneas autogeneradas erróneas acá (mismo falso
    # positivo documentado en cada migración desde purchasing —
    # autogenerate no ve reflejados correctamente objetos creados vía
    # op.execute() crudo en migraciones previas: ck_company_packages_
    # package/status, el índice GIN ix_contacts_name_trgm,
    # ck_stock_levels_reserved_quantity_valid).

    # -----------------------------------------------------------------
    # RLS + tenant_isolation + grants — mismo patrón que todas las
    # migraciones anteriores, las 3 tablas nuevas de pipeline.
    # -----------------------------------------------------------------
    pipeline_tables = ("stages", "opportunities", "activities")
    for table_name in pipeline_tables:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table_name}
                USING (company_id = current_setting('app.current_company_id', true)::bigint)
                WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
            """
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO erp_app")


def downgrade() -> None:
    """Downgrade schema."""
    pipeline_tables = ("stages", "opportunities", "activities")
    for table_name in pipeline_tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table_name}")
        op.execute(f"ALTER TABLE {table_name} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_opportunity_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_contact_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_company_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_opportunities_stage_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_contact_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_stages_company_id'), table_name='stages')
    op.drop_table('stages')
    # ### end Alembic commands ###
