"""medical: teleconsultation_sessions

Revision ID: eb73bbb40cbc
Revises: 1d195275df90
Create Date: 2026-09-10 20:12:41.614583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb73bbb40cbc'
down_revision: Union[str, Sequence[str], None] = '1d195275df90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teleconsultation_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('professional_user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('room_external_id', sa.String(length=200), nullable=False),
    sa.Column('join_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'active', 'ended', 'cancelled')", name='ck_teleconsultation_sessions_status'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['professional_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teleconsultation_sessions_appointment_id'), 'teleconsultation_sessions', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_teleconsultation_sessions_company_id'), 'teleconsultation_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_teleconsultation_sessions_patient_contact_id'), 'teleconsultation_sessions', ['patient_contact_id'], unique=False)
    op.create_index(op.f('ix_teleconsultation_sessions_professional_user_id'), 'teleconsultation_sessions', ['professional_user_id'], unique=False)
    # ### end Alembic commands ###
    # NOTA: se removieron 4 líneas autogeneradas erróneas acá (mismo falso
    # positivo documentado en cada migración desde purchasing).

    op.execute("ALTER TABLE teleconsultation_sessions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE teleconsultation_sessions FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON teleconsultation_sessions
            USING (company_id = current_setting('app.current_company_id', true)::bigint)
            WITH CHECK (company_id = current_setting('app.current_company_id', true)::bigint)
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON teleconsultation_sessions TO erp_app")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON teleconsultation_sessions")
    op.execute("ALTER TABLE teleconsultation_sessions NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE teleconsultation_sessions DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teleconsultation_sessions_professional_user_id'), table_name='teleconsultation_sessions')
    op.drop_index(op.f('ix_teleconsultation_sessions_patient_contact_id'), table_name='teleconsultation_sessions')
    op.drop_index(op.f('ix_teleconsultation_sessions_company_id'), table_name='teleconsultation_sessions')
    op.drop_index(op.f('ix_teleconsultation_sessions_appointment_id'), table_name='teleconsultation_sessions')
    op.drop_table('teleconsultation_sessions')
    # ### end Alembic commands ###
